# Generated by Django 5.0.2 on 2024-02-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(default=None, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(default=None, null=True)),
                ('status', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('detail', models.CharField(default='', max_length=255, null=True)),
                ('distance', models.FloatField()),
                ('img_res', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('quantity_sold', models.IntegerField(null=True)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('star', models.FloatField(default=None, null=True)),
                ('time', models.IntegerField(default=None, null=True)),
                ('time_close', models.CharField(max_length=255)),
                ('time_start', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'restaurant_entity',
            },
        ),
        migrations.CreateModel(
            name='TypeFoodEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(default=None, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(default=None, null=True)),
                ('status', models.BooleanField()),
                ('img_type', models.CharField(max_length=255)),
                ('name_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_food_entity',
            },
        ),
        migrations.CreateModel(
            name='FoodEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('modified_by', models.CharField(default=None, max_length=255, null=True)),
                ('modified_date', models.DateTimeField(default=None, null=True)),
                ('status', models.BooleanField(default=True)),
                ('detail', models.CharField(default='', max_length=255, null=True)),
                ('food_name', models.CharField(max_length=255)),
                ('img_food', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity_purchased', models.IntegerField(null=True)),
                ('star', models.FloatField(default=None, null=True)),
                ('restaurant_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.restaurantentity')),
                ('type_food_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.typefoodentity')),
            ],
            options={
                'db_table': 'food_entity',
            },
        ),
        migrations.CreateModel(
            name='ToppingEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('food_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.foodentity')),
                ('restaurant_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.restaurantentity')),
            ],
            options={
                'db_table': 'topping_entity',
            },
        ),
    ]
